// flow-typed signature: 4cd060e174bcf4e569d4a1b8b3fbd98b
// flow-typed version: <<STUB>>/cli-progress_v^2.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cli-progress/cli-progress' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/Bar' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/ETA' {
  declare module.exports: any;
}

declare module 'cli-progress/lib/Terminal' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/index' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/legacy' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/rect' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/shades-classic' {
  declare module.exports: any;
}

declare module 'cli-progress/presets/shades-grey' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cli-progress/cli-progress.js' {
  declare module.exports: $Exports<'cli-progress/cli-progress'>;
}
declare module 'cli-progress/lib/Bar.js' {
  declare module.exports: $Exports<'cli-progress/lib/Bar'>;
}
declare module 'cli-progress/lib/ETA.js' {
  declare module.exports: $Exports<'cli-progress/lib/ETA'>;
}
declare module 'cli-progress/lib/Terminal.js' {
  declare module.exports: $Exports<'cli-progress/lib/Terminal'>;
}
declare module 'cli-progress/presets/index.js' {
  declare module.exports: $Exports<'cli-progress/presets/index'>;
}
declare module 'cli-progress/presets/legacy.js' {
  declare module.exports: $Exports<'cli-progress/presets/legacy'>;
}
declare module 'cli-progress/presets/rect.js' {
  declare module.exports: $Exports<'cli-progress/presets/rect'>;
}
declare module 'cli-progress/presets/shades-classic.js' {
  declare module.exports: $Exports<'cli-progress/presets/shades-classic'>;
}
declare module 'cli-progress/presets/shades-grey.js' {
  declare module.exports: $Exports<'cli-progress/presets/shades-grey'>;
}
